# Generated by Django 4.0.5 on 2022-06-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('roleoftheUser', models.CharField(choices=[('Employee', 'Employee'), ('StudentCounselor', 'StudentCounselor'), ('SystemAdmin', 'SystemAdmin')], max_length=20)),
            ],
        ),
    ]
