# Generated by Django 4.0.5 on 2022-06-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_enquiryform'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryform',
            name='interst',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
