# Generated by Django 4.0.5 on 2022-06-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_enquiryform_interst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
