# Generated by Django 4.0.5 on 2022-06-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_rename_email_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='claimedEmployee',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('EID', models.IntegerField()),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.enquiryform')),
            ],
        ),
    ]
