# Generated by Django 4.0.5 on 2022-06-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_claimedemployee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimedemployee',
            name='EID',
        ),
    ]
