# Generated by Django 4.0.5 on 2022-06-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_remove_claimedemployee_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryform',
            name='interst',
            field=models.CharField(max_length=100),
        ),
    ]
